//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int IDAboutUs { get; set; }
        public string NameAboutUs { get; set; }
        public string ImgAboutUS { get; set; }
        public string ShortDes { get; set; }
        public string FullDes { get; set; }
    }
}
