//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        public int IDBrand { get; set; }
        public string NameBrand { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<bool> Title { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
