//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int IDContact { get; set; }
        public Nullable<int> IDAccount { get; set; }
        public string PhoneContact { get; set; }
        public string AddressContact { get; set; }
        public string Message { get; set; }
        public string LinkGoogleMap { get; set; }
        public string Description { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
