//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Categogies = new HashSet<Categogy>();
            this.ShoppingCarts = new HashSet<ShoppingCart>();
            this.Brands = new HashSet<Brand>();
        }
    
        public int IDProduct { get; set; }
        public string NameProduct { get; set; }
        public string ImgProduct { get; set; }
        public Nullable<double> Price { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Rating { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<bool> IsBestSaller { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categogy> Categogies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brand> Brands { get; set; }
    }
}
