//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace final_project.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public int IDShoppingCart { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<double> PriceTotal { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> IDDiscount { get; set; }
    
        public virtual Discount Discount { get; set; }
        public virtual Product Product { get; set; }
    }
}
